### ISSUE TITLE
Add single or double precision option

### ISSUE THREAD

**Issue by dtseidl** [dicengine/dicegui#10]
In many applications the single precision version of the DICe yields acceptable results at a lower computational cost.

It would be nice to have the option to run with either the double or single precision version of the code in the GUI. Both executables and their associated libraries (that are precision-dependent) would necessarily need to be packaged with the installer, so either version could be utilized via the command line as well.

**Comment by dicengine** [comment]
The user can build a single precision executable and then in the .dice.js file in the home directory set the following variable for DICe to use this single precision build:

var execPathOverride = <path to single precision build>;
