### ISSUE TITLE
Hardcoded path in cal.js

### ISSUE THREAD

**Issue by haemishkyd** [dicengine/dicegui#12]
In cal.js (line 75) the path sent to fs.watch is hardcoded to a specific users path. This caused me issues in performing camera calibration since the javascript crashed at this point.
I am using Ubuntu 18.04 with electron 1.7.10. 
The code in question seems to have been introduced in commit a619b31ea5d9525f4ed273c6037a50fb5716d534 (Aug 28, 2019)
It is possible that it is not an issue to have this hardcoded path in the code but I found it fixed it when I changed this to a path present on my computer.

**Comment by dicengine** [comment]
Thanks for noticing this mistake! I just committed a fix

**Comment by haemishkyd** [comment]
Thanks.
