### ISSUE TITLE
Issue setting a work dir. 'Uncaught Error: ENOENT: no such file or directory, scandir 'null'

### ISSUE THREAD

**Issue by manpan-1** [dicengine/dicegui#16]
I get the following error when trying to perform specific actions on a session, for example when I click run:

"Error: an error ocurred creating the file ENOENT: no such file or directory, open 'null/input.xml' or ...'null/params.xml'

Here is the console output:
```
fs.js:125 Uncaught Error: ENOENT: no such file or directory, scandir 'null'
    at Object.readdirSync (fs.js:795)
    at Object.fs.readdirSync (electron/js2c/asar.js:643)
    at Object.fs.readdirSync (electron/js2c/asar.js:643)
    at callDICeExec (dice.js:254)
    at writeSubsetFile (dice.js:1171)
    at dice.js:1036
    at fs.js:1186
    at FSReqCallback.oncomplete (fs.js:153)

```
I suppose that the files are not meant to be under 'null'.

Though I have tried setting a working dir, the indication on the bottom of the options pane remains 'null', which I guess causes the above behaviour. No errors or warnings returned.

opensuse Leap 15.1
node v10.16.3
npm 6.12.0
electron v6.0.12

**Comment by manpan-1** [comment]
The problem comes from utils.js:
```

$("#changeWorkingDirLi").click(function(){
    var path =  dialog.showOpenDialog({defaultPath: workingDirectory, properties: ['openDirectory','createDirectory']});
    if(path){
        workingDirectory = path[0];
        updateWorkingDirLabel();
        var fileName = fullPath('','input.xml');
        fs.stat(fileName, function(err, stat) {
            if(err == null) {
                if (confirm('load the existing input files in this working directory?')) {
                    console.log('loading existing input file if it exists: ' + fileName);
                    parse_input_xml_file(fileName);
                }else{
                    return false;
                }
            }else {
            }
        });
    }
});

```

For some reason it won't fetch the selected path from the dialog window. I'm on KDE Plasma 5.12.8 with qt 5.9.7.

Setting the `workingDirectory` manually and executing  `updateWorkingDirLabel()` solves the issue.

**Comment by dicengine** [comment]
See the comments in Issue #15
