### ISSUE TITLE
Image folder in calibration does nothing

### ISSUE THREAD

**Issue by sleach3** [dicengine/dicegui#19]
I built DICe on a Jetson Xavier board running linux. I am trying to run some tests with the GUI to make sure the system is going to work with the Jetson board. The issue I am having right now is when I try to select the image folder for calibration images nothing happens. I don't get any errors, I just don't get a pop up window or any feedback.

**Comment by dicengine** [comment]
Can you open the developer tools from the GUI and see if there is any console output?

**Comment by sleach3** [comment]
How would I open the developer tools?

**Comment by dicengine** [comment]
It's in the electron menu at the top of the GUI under View->Toggle Developer Tools. That should open a panel on the right side of the GUI that has several tabs in the upper right corner. One of those tabs is the console tab.

**Comment by sleach3** [comment]
![console](https://user-images.githubusercontent.com/22305725/68783711-665c0380-0609-11ea-8b46-2dcf366e99df.png)

**Comment by sleach3** [comment]
![console_3](https://user-images.githubusercontent.com/22305725/68784863-40cff980-060b-11ea-9ca9-f706631c7570.png)
This is the output from the console of the calibration window

**Comment by dicengine** [comment]
Have you installed Node.js on this device?

**Comment by sleach3** [comment]
I just double checked and I have. It seems to be failing on several lines that involve the OS.

**Comment by dicengine** [comment]
It's not the operating system it's on calls to the os methods in Node.js. These involve things like creating directories, etc. You may need to do some googling on the error you're getting as it seems more related to the Node.js utilities not being available or accessible.

**Comment by sleach3** [comment]
After some digging, I was able to determine that the hot fix applied in commit 88ad320 needed to be put into all files that create a new window.

**Comment by dicengine** [comment]
I've added the fix to all calls to BrowserWinodw let me know if this didn't fix the issue and I can re-open the issue
