### ISSUE TITLE
Image folder selection button in calibration module not working

### ISSUE THREAD

**Issue by bvanmieg** [dicengine/dicegui#21]
The button to select an image folder in the calibration module is not working anymore when you start a project from scratch.

This is the output in the developers tool console:

fs.js:1412 Uncaught Error: watch /home/bvm/TEST/CALIBXXX/.dice ENOENT
    at exports._errnoException (util.js:1050:11)
    at FSWatcher.start (fs.js:1410:19)
    at Object.fs.watch (fs.js:1436:11)
    at file:///home/bvm/DICE_GUI/js/cal.js:92:4

It seems that during one of the last changes, the gui is looking for a path/.dice (hidden folder).
This folder does however not yet exist when starting a new correlation project.
When manually making a 'dummy' folder called '.dice', the button works again.

I'm not experienced enough with js to solve this but I guess this should be pretty easy.

Bart

**Comment by dicengine** [comment]
Thanks for catching this. Fixed in https://github.com/dicengine/dicegui/commit/897998be734e213ac7d8984621ed311edd429ddc. I rebuilt the installers for version 2.0-beta.16 as well.
