### ISSUE TITLE
GUI for dice-2.0-beta.8

### ISSUE THREAD

**Issue by zhangkmsjtu** [dicengine/dicegui#23]
How to download the dicegui source code corresponding to dice-2.0-beta.8?

**Comment by dicengine** [comment]
Unfortunately, we don't have a simple way to connect GUI commits to the exec releases, but based on the Date of DICe-2.0-beta.8 the closest commit in the GUI is this one: https://github.com/dicengine/dicegui/commit/22bd8a1ce724b9a501f087f442f2a0736c06aa75
