### ISSUE TITLE
Output Scaled to Desired Dimension

### ISSUE THREAD

**Issue by dac0022** [dicengine/dicegui#4]
Have an input in the GUI for scaling from pixels to desired length in the output text file.

**Comment by dicengine** [comment]
The latest release lets the user calibrate for 2D analysis. It's not as simple as providing a scaling from pixels to desired length, but one could create a camera file that essentially does this. The way it's set up now is that DICe uses the camera's intrinsic parameters (focal length, skew, etc.) in combination with a pose estimation for the surface of the sample to determine the coordinates of each subset in physical space. If calibration is enabled for 2d, the results are output in model coordinates.
